apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SpringBootKotlinDemo
  annotations:
    github.com/project-slug: kenwalger/SpringBootKotlinDemo
spec:
  type: other
  lifecycle: unknown
  owner: guests
